//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace office360.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccFeeChallan
    {
        public int Id { get; set; }
        public Nullable<System.Guid> GuID { get; set; }
        public string Code { get; set; }
        public string InvoiceNo { get; set; }
        public string Description { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> RegistrationTypeId { get; set; }
        public Nullable<int> ClassRegistrationId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> FeeStructureId { get; set; }
        public Nullable<decimal> GrossRecievable { get; set; }
        public Nullable<decimal> LateFee { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> NetRecievable { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> DocumentStatus { get; set; }
        public Nullable<int> DocType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
