//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace office360.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccFeeChallanDetail
    {
        public int Id { get; set; }
        public Nullable<System.Guid> GuID { get; set; }
        public Nullable<int> FeeChallanId { get; set; }
        public Nullable<int> FeeTypeId { get; set; }
        public Nullable<decimal> ActualAmount { get; set; }
        public Nullable<decimal> ChargedAmount { get; set; }
        public Nullable<decimal> Difference { get; set; }
    }
}
