//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace office360.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccStudentOB
    {
        public int Id { get; set; }
        public Nullable<System.Guid> GuID { get; set; }
        public Nullable<int> FeeTypeId { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> ClassRegistrationId { get; set; }
    }
}
