//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace office360.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppStudent
    {
        public int Id { get; set; }
        public Nullable<System.Guid> GuID { get; set; }
        public Nullable<int> SessionId { get; set; }
        public string Code { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CnicNo_FormBNo { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> MartialStatusId { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public string ResedenitalAddress { get; set; }
        public string MobileNumber { get; set; }
        public string EmailAddress { get; set; }
        public string ParentName { get; set; }
        public string ParentCnic { get; set; }
        public Nullable<int> ParentStudyLevelId { get; set; }
        public Nullable<int> OccupationId { get; set; }
        public Nullable<int> RelationshipId { get; set; }
        public Nullable<decimal> MonthlyIncome { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> DocumentStatus { get; set; }
        public Nullable<int> DocType { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
