//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace office360.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralBranchSetting
    {
        public int Id { get; set; }
        public Nullable<System.Guid> GuID { get; set; }
        public Nullable<int> CampusId { get; set; }
        public Nullable<int> RollCallSystemId { get; set; }
        public Nullable<int> BillingMethodId { get; set; }
        public string StudyLevelIds { get; set; }
        public string StudyGroupIds { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public Nullable<System.DateTime> ExpiredOn { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> PolicyPeriodId { get; set; }
        public Nullable<int> ChallanMethodId { get; set; }
    }
}
