//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace office360.Models.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SESEntities : DbContext
    {
        public SESEntities()
            : base("name=SESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccFeeChallan> AccFeeChallan { get; set; }
        public virtual DbSet<AccFeeChallanDetail> AccFeeChallanDetail { get; set; }
        public virtual DbSet<AccFeeStructure> AccFeeStructure { get; set; }
        public virtual DbSet<AccFeeStructureDetail> AccFeeStructureDetail { get; set; }
        public virtual DbSet<AccJournal> AccJournal { get; set; }
        public virtual DbSet<AccLedgerFee> AccLedgerFee { get; set; }
        public virtual DbSet<AccStudentOB> AccStudentOB { get; set; }
        public virtual DbSet<AppClass> AppClass { get; set; }
        public virtual DbSet<AppClassRegistration> AppClassRegistration { get; set; }
        public virtual DbSet<AppSession> AppSession { get; set; }
        public virtual DbSet<AppStudent> AppStudent { get; set; }
        public virtual DbSet<GeneralBranch> GeneralBranch { get; set; }
        public virtual DbSet<GeneralBranchSetting> GeneralBranchSetting { get; set; }
        public virtual DbSet<GeneralCompany> GeneralCompany { get; set; }
        public virtual DbSet<GeneralEmailSetting> GeneralEmailSetting { get; set; }
        public virtual DbSet<GeneralRightSetting> GeneralRightSetting { get; set; }
        public virtual DbSet<GeneralUser> GeneralUser { get; set; }
        public virtual DbSet<GeneralUserRight> GeneralUserRight { get; set; }
        public virtual DbSet<StructureCOAAccount> StructureCOAAccount { get; set; }
        public virtual DbSet<StructureFeeType> StructureFeeType { get; set; }
        public virtual DbSet<BillingMethod> BillingMethod { get; set; }
        public virtual DbSet<CampusType> CampusType { get; set; }
        public virtual DbSet<ChallanMethod> ChallanMethod { get; set; }
        public virtual DbSet<ChargingMethod> ChargingMethod { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<CoaCatagory> CoaCatagory { get; set; }
        public virtual DbSet<CoaType> CoaType { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<DocType> DocType { get; set; }
        public virtual DbSet<DocumentStatus> DocumentStatus { get; set; }
        public virtual DbSet<EducationBoard> EducationBoard { get; set; }
        public virtual DbSet<EnrollmentType> EnrollmentType { get; set; }
        public virtual DbSet<FeeCatagory> FeeCatagory { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<MartialStatus> MartialStatus { get; set; }
        public virtual DbSet<Occupation> Occupation { get; set; }
        public virtual DbSet<OrganizationType> OrganizationType { get; set; }
        public virtual DbSet<PolicyPeriod> PolicyPeriod { get; set; }
        public virtual DbSet<RegistrationType> RegistrationType { get; set; }
        public virtual DbSet<Relationship> Relationship { get; set; }
        public virtual DbSet<Religion> Religion { get; set; }
        public virtual DbSet<Right> Right { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RollCallSystem> RollCallSystem { get; set; }
        public virtual DbSet<StudyGroup> StudyGroup { get; set; }
        public virtual DbSet<StudyLevel> StudyLevel { get; set; }
        public virtual DbSet<URLType> URLType { get; set; }
        public virtual DbSet<WHTaxPolicy> WHTaxPolicy { get; set; }
        public virtual DbSet<WorkingShift> WorkingShift { get; set; }
    
        [DbFunction("SESEntities", "fn_CodeSplitByCommaAsINT")]
        public virtual IQueryable<fn_CodeSplitByCommaAsINT_Result> fn_CodeSplitByCommaAsINT(string psCSString)
        {
            var psCSStringParameter = psCSString != null ?
                new ObjectParameter("psCSString", psCSString) :
                new ObjectParameter("psCSString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_CodeSplitByCommaAsINT_Result>("[SESEntities].[fn_CodeSplitByCommaAsINT](@psCSString)", psCSStringParameter);
        }
    
        [DbFunction("SESEntities", "fn_CodeSplitByCommaAsUniqueIdentifier")]
        public virtual IQueryable<fn_CodeSplitByCommaAsUniqueIdentifier_Result> fn_CodeSplitByCommaAsUniqueIdentifier(string psCSString)
        {
            var psCSStringParameter = psCSString != null ?
                new ObjectParameter("psCSString", psCSString) :
                new ObjectParameter("psCSString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_CodeSplitByCommaAsUniqueIdentifier_Result>("[SESEntities].[fn_CodeSplitByCommaAsUniqueIdentifier](@psCSString)", psCSStringParameter);
        }
    
        [DbFunction("SESEntities", "fn_GetCommaSepratedValuesInList")]
        public virtual IQueryable<fn_GetCommaSepratedValuesInList_Result> fn_GetCommaSepratedValuesInList(string psCSString)
        {
            var psCSStringParameter = psCSString != null ?
                new ObjectParameter("psCSString", psCSString) :
                new ObjectParameter("psCSString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_GetCommaSepratedValuesInList_Result>("[SESEntities].[fn_GetCommaSepratedValuesInList](@psCSString)", psCSStringParameter);
        }
    
        public virtual int AccFeeChallan_Insert(Nullable<System.Guid> guId, string description, Nullable<int> sessionId, Nullable<int> classId, Nullable<int> registrationTypeId, Nullable<int> classRegistrationId, Nullable<System.DateTime> transactionDate, Nullable<System.DateTime> dueDate, Nullable<System.DateTime> expiryDate, Nullable<int> feeStructureId, Nullable<decimal> grossRecievable, Nullable<decimal> lateFee, Nullable<decimal> discount, Nullable<decimal> netRecievable, Nullable<int> createdBy, Nullable<int> documentStatus, Nullable<int> docType, Nullable<int> branchId, Nullable<int> companyId, ObjectParameter response)
        {
            var guIdParameter = guId.HasValue ?
                new ObjectParameter("GuId", guId) :
                new ObjectParameter("GuId", typeof(System.Guid));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var sessionIdParameter = sessionId.HasValue ?
                new ObjectParameter("SessionId", sessionId) :
                new ObjectParameter("SessionId", typeof(int));
    
            var classIdParameter = classId.HasValue ?
                new ObjectParameter("ClassId", classId) :
                new ObjectParameter("ClassId", typeof(int));
    
            var registrationTypeIdParameter = registrationTypeId.HasValue ?
                new ObjectParameter("RegistrationTypeId", registrationTypeId) :
                new ObjectParameter("RegistrationTypeId", typeof(int));
    
            var classRegistrationIdParameter = classRegistrationId.HasValue ?
                new ObjectParameter("ClassRegistrationId", classRegistrationId) :
                new ObjectParameter("ClassRegistrationId", typeof(int));
    
            var transactionDateParameter = transactionDate.HasValue ?
                new ObjectParameter("TransactionDate", transactionDate) :
                new ObjectParameter("TransactionDate", typeof(System.DateTime));
    
            var dueDateParameter = dueDate.HasValue ?
                new ObjectParameter("DueDate", dueDate) :
                new ObjectParameter("DueDate", typeof(System.DateTime));
    
            var expiryDateParameter = expiryDate.HasValue ?
                new ObjectParameter("ExpiryDate", expiryDate) :
                new ObjectParameter("ExpiryDate", typeof(System.DateTime));
    
            var feeStructureIdParameter = feeStructureId.HasValue ?
                new ObjectParameter("FeeStructureId", feeStructureId) :
                new ObjectParameter("FeeStructureId", typeof(int));
    
            var grossRecievableParameter = grossRecievable.HasValue ?
                new ObjectParameter("GrossRecievable", grossRecievable) :
                new ObjectParameter("GrossRecievable", typeof(decimal));
    
            var lateFeeParameter = lateFee.HasValue ?
                new ObjectParameter("LateFee", lateFee) :
                new ObjectParameter("LateFee", typeof(decimal));
    
            var discountParameter = discount.HasValue ?
                new ObjectParameter("Discount", discount) :
                new ObjectParameter("Discount", typeof(decimal));
    
            var netRecievableParameter = netRecievable.HasValue ?
                new ObjectParameter("NetRecievable", netRecievable) :
                new ObjectParameter("NetRecievable", typeof(decimal));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var documentStatusParameter = documentStatus.HasValue ?
                new ObjectParameter("DocumentStatus", documentStatus) :
                new ObjectParameter("DocumentStatus", typeof(int));
    
            var docTypeParameter = docType.HasValue ?
                new ObjectParameter("DocType", docType) :
                new ObjectParameter("DocType", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AccFeeChallan_Insert", guIdParameter, descriptionParameter, sessionIdParameter, classIdParameter, registrationTypeIdParameter, classRegistrationIdParameter, transactionDateParameter, dueDateParameter, expiryDateParameter, feeStructureIdParameter, grossRecievableParameter, lateFeeParameter, discountParameter, netRecievableParameter, createdByParameter, documentStatusParameter, docTypeParameter, branchIdParameter, companyIdParameter, response);
        }
    
        public virtual int AccFeeChallanDetail_Insert(Nullable<int> feeChallanId, Nullable<int> feeTypeId, Nullable<decimal> actualAmount, Nullable<decimal> chargedAmount, Nullable<decimal> difference)
        {
            var feeChallanIdParameter = feeChallanId.HasValue ?
                new ObjectParameter("FeeChallanId", feeChallanId) :
                new ObjectParameter("FeeChallanId", typeof(int));
    
            var feeTypeIdParameter = feeTypeId.HasValue ?
                new ObjectParameter("FeeTypeId", feeTypeId) :
                new ObjectParameter("FeeTypeId", typeof(int));
    
            var actualAmountParameter = actualAmount.HasValue ?
                new ObjectParameter("ActualAmount", actualAmount) :
                new ObjectParameter("ActualAmount", typeof(decimal));
    
            var chargedAmountParameter = chargedAmount.HasValue ?
                new ObjectParameter("ChargedAmount", chargedAmount) :
                new ObjectParameter("ChargedAmount", typeof(decimal));
    
            var differenceParameter = difference.HasValue ?
                new ObjectParameter("Difference", difference) :
                new ObjectParameter("Difference", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AccFeeChallanDetail_Insert", feeChallanIdParameter, feeTypeIdParameter, actualAmountParameter, chargedAmountParameter, differenceParameter);
        }
    
        public virtual ObjectResult<AccFeeStructure_GetListByParam_Result> AccFeeStructure_GetListByParam(string dB_IF_PARAM, Nullable<int> companyId, Nullable<int> branchId, string allowedCampusIds)
        {
            var dB_IF_PARAMParameter = dB_IF_PARAM != null ?
                new ObjectParameter("DB_IF_PARAM", dB_IF_PARAM) :
                new ObjectParameter("DB_IF_PARAM", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var allowedCampusIdsParameter = allowedCampusIds != null ?
                new ObjectParameter("AllowedCampusIds", allowedCampusIds) :
                new ObjectParameter("AllowedCampusIds", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AccFeeStructure_GetListByParam_Result>("AccFeeStructure_GetListByParam", dB_IF_PARAMParameter, companyIdParameter, branchIdParameter, allowedCampusIdsParameter);
        }
    
        public virtual ObjectResult<AccFeeStructure_GetListBySearch_Result> AccFeeStructure_GetListBySearch(Nullable<int> companyId, Nullable<int> branchId, Nullable<int> inputTypeId, string inputText)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var inputTypeIdParameter = inputTypeId.HasValue ?
                new ObjectParameter("InputTypeId", inputTypeId) :
                new ObjectParameter("InputTypeId", typeof(int));
    
            var inputTextParameter = inputText != null ?
                new ObjectParameter("InputText", inputText) :
                new ObjectParameter("InputText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AccFeeStructure_GetListBySearch_Result>("AccFeeStructure_GetListBySearch", companyIdParameter, branchIdParameter, inputTypeIdParameter, inputTextParameter);
        }
    
        public virtual int AccJournal_Insert(string code, Nullable<System.DateTime> transactionDate, string folioNo, string reference, string description, Nullable<int> debitAccountId, Nullable<decimal> debitAmount, Nullable<int> creditAccountId, Nullable<decimal> creditAmount, Nullable<decimal> balanceAmount, Nullable<int> createdBy, Nullable<int> docType, Nullable<int> branchId, Nullable<int> companyId)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var transactionDateParameter = transactionDate.HasValue ?
                new ObjectParameter("TransactionDate", transactionDate) :
                new ObjectParameter("TransactionDate", typeof(System.DateTime));
    
            var folioNoParameter = folioNo != null ?
                new ObjectParameter("FolioNo", folioNo) :
                new ObjectParameter("FolioNo", typeof(string));
    
            var referenceParameter = reference != null ?
                new ObjectParameter("Reference", reference) :
                new ObjectParameter("Reference", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var debitAccountIdParameter = debitAccountId.HasValue ?
                new ObjectParameter("DebitAccountId", debitAccountId) :
                new ObjectParameter("DebitAccountId", typeof(int));
    
            var debitAmountParameter = debitAmount.HasValue ?
                new ObjectParameter("DebitAmount", debitAmount) :
                new ObjectParameter("DebitAmount", typeof(decimal));
    
            var creditAccountIdParameter = creditAccountId.HasValue ?
                new ObjectParameter("CreditAccountId", creditAccountId) :
                new ObjectParameter("CreditAccountId", typeof(int));
    
            var creditAmountParameter = creditAmount.HasValue ?
                new ObjectParameter("CreditAmount", creditAmount) :
                new ObjectParameter("CreditAmount", typeof(decimal));
    
            var balanceAmountParameter = balanceAmount.HasValue ?
                new ObjectParameter("BalanceAmount", balanceAmount) :
                new ObjectParameter("BalanceAmount", typeof(decimal));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var docTypeParameter = docType.HasValue ?
                new ObjectParameter("DocType", docType) :
                new ObjectParameter("DocType", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AccJournal_Insert", codeParameter, transactionDateParameter, folioNoParameter, referenceParameter, descriptionParameter, debitAccountIdParameter, debitAmountParameter, creditAccountIdParameter, creditAmountParameter, balanceAmountParameter, createdByParameter, docTypeParameter, branchIdParameter, companyIdParameter);
        }
    
        public virtual ObjectResult<AppClass_GetListByParam_Result> AppClass_GetListByParam(string dB_IF_PARAM, Nullable<int> companyId, Nullable<int> branchId, Nullable<int> appSessionId, string classIds)
        {
            var dB_IF_PARAMParameter = dB_IF_PARAM != null ?
                new ObjectParameter("DB_IF_PARAM", dB_IF_PARAM) :
                new ObjectParameter("DB_IF_PARAM", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var appSessionIdParameter = appSessionId.HasValue ?
                new ObjectParameter("AppSessionId", appSessionId) :
                new ObjectParameter("AppSessionId", typeof(int));
    
            var classIdsParameter = classIds != null ?
                new ObjectParameter("ClassIds", classIds) :
                new ObjectParameter("ClassIds", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AppClass_GetListByParam_Result>("AppClass_GetListByParam", dB_IF_PARAMParameter, companyIdParameter, branchIdParameter, appSessionIdParameter, classIdsParameter);
        }
    
        public virtual int AppClass_Insert(string description, Nullable<int> branchId, Nullable<int> companyId, Nullable<int> createdBy, Nullable<int> studyLevelId, Nullable<int> studyGroupId, ObjectParameter code_, ObjectParameter response)
        {
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var studyLevelIdParameter = studyLevelId.HasValue ?
                new ObjectParameter("StudyLevelId", studyLevelId) :
                new ObjectParameter("StudyLevelId", typeof(int));
    
            var studyGroupIdParameter = studyGroupId.HasValue ?
                new ObjectParameter("StudyGroupId", studyGroupId) :
                new ObjectParameter("StudyGroupId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AppClass_Insert", descriptionParameter, branchIdParameter, companyIdParameter, createdByParameter, studyLevelIdParameter, studyGroupIdParameter, code_, response);
        }
    
        public virtual int AppClassRegistration_Insert(Nullable<int> sessionId, Nullable<int> studentId, Nullable<int> classId, Nullable<int> documentStatus, Nullable<int> docType, Nullable<int> createdBy, Nullable<int> branchId, Nullable<int> companyId, ObjectParameter response)
        {
            var sessionIdParameter = sessionId.HasValue ?
                new ObjectParameter("SessionId", sessionId) :
                new ObjectParameter("SessionId", typeof(int));
    
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            var classIdParameter = classId.HasValue ?
                new ObjectParameter("ClassId", classId) :
                new ObjectParameter("ClassId", typeof(int));
    
            var documentStatusParameter = documentStatus.HasValue ?
                new ObjectParameter("DocumentStatus", documentStatus) :
                new ObjectParameter("DocumentStatus", typeof(int));
    
            var docTypeParameter = docType.HasValue ?
                new ObjectParameter("DocType", docType) :
                new ObjectParameter("DocType", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AppClassRegistration_Insert", sessionIdParameter, studentIdParameter, classIdParameter, documentStatusParameter, docTypeParameter, createdByParameter, branchIdParameter, companyIdParameter, response);
        }
    
        public virtual int AppSession_Insert(string description, Nullable<int> campusId, Nullable<System.DateTime> sessionStartOn, Nullable<System.DateTime> sessionEndOn, Nullable<int> documentStatus, Nullable<int> companyId, Nullable<int> branchId, Nullable<int> createdBy, string classIds, Nullable<int> enrollmentTypeId, Nullable<System.DateTime> effectiveFrom, Nullable<System.DateTime> expiredOn, ObjectParameter response, ObjectParameter code_)
        {
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var campusIdParameter = campusId.HasValue ?
                new ObjectParameter("CampusId", campusId) :
                new ObjectParameter("CampusId", typeof(int));
    
            var sessionStartOnParameter = sessionStartOn.HasValue ?
                new ObjectParameter("SessionStartOn", sessionStartOn) :
                new ObjectParameter("SessionStartOn", typeof(System.DateTime));
    
            var sessionEndOnParameter = sessionEndOn.HasValue ?
                new ObjectParameter("SessionEndOn", sessionEndOn) :
                new ObjectParameter("SessionEndOn", typeof(System.DateTime));
    
            var documentStatusParameter = documentStatus.HasValue ?
                new ObjectParameter("DocumentStatus", documentStatus) :
                new ObjectParameter("DocumentStatus", typeof(int));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var classIdsParameter = classIds != null ?
                new ObjectParameter("ClassIds", classIds) :
                new ObjectParameter("ClassIds", typeof(string));
    
            var enrollmentTypeIdParameter = enrollmentTypeId.HasValue ?
                new ObjectParameter("EnrollmentTypeId", enrollmentTypeId) :
                new ObjectParameter("EnrollmentTypeId", typeof(int));
    
            var effectiveFromParameter = effectiveFrom.HasValue ?
                new ObjectParameter("EffectiveFrom", effectiveFrom) :
                new ObjectParameter("EffectiveFrom", typeof(System.DateTime));
    
            var expiredOnParameter = expiredOn.HasValue ?
                new ObjectParameter("ExpiredOn", expiredOn) :
                new ObjectParameter("ExpiredOn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AppSession_Insert", descriptionParameter, campusIdParameter, sessionStartOnParameter, sessionEndOnParameter, documentStatusParameter, companyIdParameter, branchIdParameter, createdByParameter, classIdsParameter, enrollmentTypeIdParameter, effectiveFromParameter, expiredOnParameter, response, code_);
        }
    
        public virtual int AppStudent_Insert(Nullable<int> sessionId, string firstName, string lastName, string cnicNo_FormBNo, Nullable<int> genderId, Nullable<System.DateTime> dOB, Nullable<int> martialStatusId, Nullable<int> religionId, Nullable<int> nationalityId, string resedenitalAddress, string mobileNumber, string emailAddress, string parentName, string parentCnic, Nullable<int> parentStudyLevelId, Nullable<int> occupationId, Nullable<int> relationshipId, Nullable<decimal> monthlyIncome, Nullable<int> documentStatus, Nullable<int> createdBy, Nullable<int> branchId, Nullable<int> companyId, Nullable<int> docType, ObjectParameter code_, ObjectParameter response, ObjectParameter studentId)
        {
            var sessionIdParameter = sessionId.HasValue ?
                new ObjectParameter("SessionId", sessionId) :
                new ObjectParameter("SessionId", typeof(int));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var cnicNo_FormBNoParameter = cnicNo_FormBNo != null ?
                new ObjectParameter("CnicNo_FormBNo", cnicNo_FormBNo) :
                new ObjectParameter("CnicNo_FormBNo", typeof(string));
    
            var genderIdParameter = genderId.HasValue ?
                new ObjectParameter("GenderId", genderId) :
                new ObjectParameter("GenderId", typeof(int));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var martialStatusIdParameter = martialStatusId.HasValue ?
                new ObjectParameter("MartialStatusId", martialStatusId) :
                new ObjectParameter("MartialStatusId", typeof(int));
    
            var religionIdParameter = religionId.HasValue ?
                new ObjectParameter("ReligionId", religionId) :
                new ObjectParameter("ReligionId", typeof(int));
    
            var nationalityIdParameter = nationalityId.HasValue ?
                new ObjectParameter("NationalityId", nationalityId) :
                new ObjectParameter("NationalityId", typeof(int));
    
            var resedenitalAddressParameter = resedenitalAddress != null ?
                new ObjectParameter("ResedenitalAddress", resedenitalAddress) :
                new ObjectParameter("ResedenitalAddress", typeof(string));
    
            var mobileNumberParameter = mobileNumber != null ?
                new ObjectParameter("MobileNumber", mobileNumber) :
                new ObjectParameter("MobileNumber", typeof(string));
    
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            var parentNameParameter = parentName != null ?
                new ObjectParameter("ParentName", parentName) :
                new ObjectParameter("ParentName", typeof(string));
    
            var parentCnicParameter = parentCnic != null ?
                new ObjectParameter("ParentCnic", parentCnic) :
                new ObjectParameter("ParentCnic", typeof(string));
    
            var parentStudyLevelIdParameter = parentStudyLevelId.HasValue ?
                new ObjectParameter("ParentStudyLevelId", parentStudyLevelId) :
                new ObjectParameter("ParentStudyLevelId", typeof(int));
    
            var occupationIdParameter = occupationId.HasValue ?
                new ObjectParameter("OccupationId", occupationId) :
                new ObjectParameter("OccupationId", typeof(int));
    
            var relationshipIdParameter = relationshipId.HasValue ?
                new ObjectParameter("RelationshipId", relationshipId) :
                new ObjectParameter("RelationshipId", typeof(int));
    
            var monthlyIncomeParameter = monthlyIncome.HasValue ?
                new ObjectParameter("MonthlyIncome", monthlyIncome) :
                new ObjectParameter("MonthlyIncome", typeof(decimal));
    
            var documentStatusParameter = documentStatus.HasValue ?
                new ObjectParameter("DocumentStatus", documentStatus) :
                new ObjectParameter("DocumentStatus", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var docTypeParameter = docType.HasValue ?
                new ObjectParameter("DocType", docType) :
                new ObjectParameter("DocType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AppStudent_Insert", sessionIdParameter, firstNameParameter, lastNameParameter, cnicNo_FormBNoParameter, genderIdParameter, dOBParameter, martialStatusIdParameter, religionIdParameter, nationalityIdParameter, resedenitalAddressParameter, mobileNumberParameter, emailAddressParameter, parentNameParameter, parentCnicParameter, parentStudyLevelIdParameter, occupationIdParameter, relationshipIdParameter, monthlyIncomeParameter, documentStatusParameter, createdByParameter, branchIdParameter, companyIdParameter, docTypeParameter, code_, response, studentId);
        }
    
        public virtual ObjectResult<Nullable<int>> DEV_CheckDuplicateRecord(string tableName, string selectColumns, string whereClause)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("TableName", tableName) :
                new ObjectParameter("TableName", typeof(string));
    
            var selectColumnsParameter = selectColumns != null ?
                new ObjectParameter("SelectColumns", selectColumns) :
                new ObjectParameter("SelectColumns", typeof(string));
    
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("DEV_CheckDuplicateRecord", tableNameParameter, selectColumnsParameter, whereClauseParameter);
        }
    
        public virtual int DEV_InsertHistory(string tableName, string columnNames, string columnValues, ObjectParameter status)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("TableName", tableName) :
                new ObjectParameter("TableName", typeof(string));
    
            var columnNamesParameter = columnNames != null ?
                new ObjectParameter("ColumnNames", columnNames) :
                new ObjectParameter("ColumnNames", typeof(string));
    
            var columnValuesParameter = columnValues != null ?
                new ObjectParameter("ColumnValues", columnValues) :
                new ObjectParameter("ColumnValues", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DEV_InsertHistory", tableNameParameter, columnNamesParameter, columnValuesParameter, status);
        }
    
        public virtual ObjectResult<Nullable<int>> DEV_UpdateRecord(string tableName, string setClause, string whereClause)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("TableName", tableName) :
                new ObjectParameter("TableName", typeof(string));
    
            var setClauseParameter = setClause != null ?
                new ObjectParameter("SetClause", setClause) :
                new ObjectParameter("SetClause", typeof(string));
    
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("DEV_UpdateRecord", tableNameParameter, setClauseParameter, whereClauseParameter);
        }
    
        public virtual ObjectResult<GeneralBranch_GetListByParam_Result> GeneralBranch_GetListByParam(string dB_IF_PARAM, Nullable<int> companyId, Nullable<int> branchId, string allowedCampusIds, Nullable<int> documentStatusBranch, Nullable<int> documentStatusSession)
        {
            var dB_IF_PARAMParameter = dB_IF_PARAM != null ?
                new ObjectParameter("DB_IF_PARAM", dB_IF_PARAM) :
                new ObjectParameter("DB_IF_PARAM", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var allowedCampusIdsParameter = allowedCampusIds != null ?
                new ObjectParameter("AllowedCampusIds", allowedCampusIds) :
                new ObjectParameter("AllowedCampusIds", typeof(string));
    
            var documentStatusBranchParameter = documentStatusBranch.HasValue ?
                new ObjectParameter("DocumentStatusBranch", documentStatusBranch) :
                new ObjectParameter("DocumentStatusBranch", typeof(int));
    
            var documentStatusSessionParameter = documentStatusSession.HasValue ?
                new ObjectParameter("DocumentStatusSession", documentStatusSession) :
                new ObjectParameter("DocumentStatusSession", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GeneralBranch_GetListByParam_Result>("GeneralBranch_GetListByParam", dB_IF_PARAMParameter, companyIdParameter, branchIdParameter, allowedCampusIdsParameter, documentStatusBranchParameter, documentStatusSessionParameter);
        }
    
        public virtual ObjectResult<GeneralBranch_GetListBySearch_Result> GeneralBranch_GetListBySearch(Nullable<int> companyId, Nullable<int> branchId, Nullable<int> inputTypeId, string inputText)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var inputTypeIdParameter = inputTypeId.HasValue ?
                new ObjectParameter("InputTypeId", inputTypeId) :
                new ObjectParameter("InputTypeId", typeof(int));
    
            var inputTextParameter = inputText != null ?
                new ObjectParameter("InputText", inputText) :
                new ObjectParameter("InputText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GeneralBranch_GetListBySearch_Result>("GeneralBranch_GetListBySearch", companyIdParameter, branchIdParameter, inputTypeIdParameter, inputTextParameter);
        }
    
        public virtual int GeneralBranch_UpSert(string dB_OperationType, Nullable<System.Guid> guID, string description, Nullable<int> campusTypeId, Nullable<int> organizationTypeId, Nullable<int> countryId, Nullable<int> cityId, string address, string contactNo, string emailAddress, string nTNNo, string remarks, Nullable<System.DateTime> createdOn, Nullable<int> createdBy, Nullable<System.DateTime> updatedOn, Nullable<int> updatedBy, Nullable<System.DateTime> effectiveFrom, Nullable<System.DateTime> expiredOn, Nullable<bool> status, Nullable<int> docType, Nullable<int> documentStatus, Nullable<int> branchId, Nullable<int> companyId, ObjectParameter response, ObjectParameter campusId)
        {
            var dB_OperationTypeParameter = dB_OperationType != null ?
                new ObjectParameter("DB_OperationType", dB_OperationType) :
                new ObjectParameter("DB_OperationType", typeof(string));
    
            var guIDParameter = guID.HasValue ?
                new ObjectParameter("GuID", guID) :
                new ObjectParameter("GuID", typeof(System.Guid));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var campusTypeIdParameter = campusTypeId.HasValue ?
                new ObjectParameter("CampusTypeId", campusTypeId) :
                new ObjectParameter("CampusTypeId", typeof(int));
    
            var organizationTypeIdParameter = organizationTypeId.HasValue ?
                new ObjectParameter("OrganizationTypeId", organizationTypeId) :
                new ObjectParameter("OrganizationTypeId", typeof(int));
    
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("CountryId", countryId) :
                new ObjectParameter("CountryId", typeof(int));
    
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(int));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var contactNoParameter = contactNo != null ?
                new ObjectParameter("ContactNo", contactNo) :
                new ObjectParameter("ContactNo", typeof(string));
    
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            var nTNNoParameter = nTNNo != null ?
                new ObjectParameter("NTNNo", nTNNo) :
                new ObjectParameter("NTNNo", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            var createdOnParameter = createdOn.HasValue ?
                new ObjectParameter("CreatedOn", createdOn) :
                new ObjectParameter("CreatedOn", typeof(System.DateTime));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var updatedOnParameter = updatedOn.HasValue ?
                new ObjectParameter("UpdatedOn", updatedOn) :
                new ObjectParameter("UpdatedOn", typeof(System.DateTime));
    
            var updatedByParameter = updatedBy.HasValue ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(int));
    
            var effectiveFromParameter = effectiveFrom.HasValue ?
                new ObjectParameter("EffectiveFrom", effectiveFrom) :
                new ObjectParameter("EffectiveFrom", typeof(System.DateTime));
    
            var expiredOnParameter = expiredOn.HasValue ?
                new ObjectParameter("ExpiredOn", expiredOn) :
                new ObjectParameter("ExpiredOn", typeof(System.DateTime));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            var docTypeParameter = docType.HasValue ?
                new ObjectParameter("DocType", docType) :
                new ObjectParameter("DocType", typeof(int));
    
            var documentStatusParameter = documentStatus.HasValue ?
                new ObjectParameter("DocumentStatus", documentStatus) :
                new ObjectParameter("DocumentStatus", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GeneralBranch_UpSert", dB_OperationTypeParameter, guIDParameter, descriptionParameter, campusTypeIdParameter, organizationTypeIdParameter, countryIdParameter, cityIdParameter, addressParameter, contactNoParameter, emailAddressParameter, nTNNoParameter, remarksParameter, createdOnParameter, createdByParameter, updatedOnParameter, updatedByParameter, effectiveFromParameter, expiredOnParameter, statusParameter, docTypeParameter, documentStatusParameter, branchIdParameter, companyIdParameter, response, campusId);
        }
    
        public virtual ObjectResult<GeneralCompany_GetDetailByParam_Result> GeneralCompany_GetDetailByParam(Nullable<int> id, string listCondition)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var listConditionParameter = listCondition != null ?
                new ObjectParameter("ListCondition", listCondition) :
                new ObjectParameter("ListCondition", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GeneralCompany_GetDetailByParam_Result>("GeneralCompany_GetDetailByParam", idParameter, listConditionParameter);
        }
    
        public virtual ObjectResult<GeneralEmailSetting_GetDetailByParam_Result> GeneralEmailSetting_GetDetailByParam(Nullable<int> companyId, string listCondition, Nullable<int> branchId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var listConditionParameter = listCondition != null ?
                new ObjectParameter("ListCondition", listCondition) :
                new ObjectParameter("ListCondition", typeof(string));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GeneralEmailSetting_GetDetailByParam_Result>("GeneralEmailSetting_GetDetailByParam", companyIdParameter, listConditionParameter, branchIdParameter);
        }
    
        public virtual int GeneralEnrollmentSetting_Insert(Nullable<int> enrollmentTypeId, Nullable<int> branchId, Nullable<int> companyId, Nullable<int> createdBy, Nullable<int> updatedBy, Nullable<System.DateTime> expiredOn)
        {
            var enrollmentTypeIdParameter = enrollmentTypeId.HasValue ?
                new ObjectParameter("EnrollmentTypeId", enrollmentTypeId) :
                new ObjectParameter("EnrollmentTypeId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var updatedByParameter = updatedBy.HasValue ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(int));
    
            var expiredOnParameter = expiredOn.HasValue ?
                new ObjectParameter("ExpiredOn", expiredOn) :
                new ObjectParameter("ExpiredOn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GeneralEnrollmentSetting_Insert", enrollmentTypeIdParameter, branchIdParameter, companyIdParameter, createdByParameter, updatedByParameter, expiredOnParameter);
        }
    
        public virtual ObjectResult<GeneralRightSetting_GetListByParam_Result> GeneralRightSetting_GetListByParam(string dB_IF_PARAM, string allowedCampusIds, Nullable<int> userId, Nullable<int> companyId, Nullable<int> uRLTypeId, Nullable<bool> status, string menu, Nullable<int> rightId, string rightPath)
        {
            var dB_IF_PARAMParameter = dB_IF_PARAM != null ?
                new ObjectParameter("DB_IF_PARAM", dB_IF_PARAM) :
                new ObjectParameter("DB_IF_PARAM", typeof(string));
    
            var allowedCampusIdsParameter = allowedCampusIds != null ?
                new ObjectParameter("AllowedCampusIds", allowedCampusIds) :
                new ObjectParameter("AllowedCampusIds", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var uRLTypeIdParameter = uRLTypeId.HasValue ?
                new ObjectParameter("URLTypeId", uRLTypeId) :
                new ObjectParameter("URLTypeId", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            var menuParameter = menu != null ?
                new ObjectParameter("Menu", menu) :
                new ObjectParameter("Menu", typeof(string));
    
            var rightIdParameter = rightId.HasValue ?
                new ObjectParameter("RightId", rightId) :
                new ObjectParameter("RightId", typeof(int));
    
            var rightPathParameter = rightPath != null ?
                new ObjectParameter("RightPath", rightPath) :
                new ObjectParameter("RightPath", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GeneralRightSetting_GetListByParam_Result>("GeneralRightSetting_GetListByParam", dB_IF_PARAMParameter, allowedCampusIdsParameter, userIdParameter, companyIdParameter, uRLTypeIdParameter, statusParameter, menuParameter, rightIdParameter, rightPathParameter);
        }
    
        public virtual ObjectResult<GeneralUser_GetDetailByParam_Result> GeneralUser_GetDetailByParam(string listCondition, Nullable<int> companyId, Nullable<bool> isLogIn, string userName, string password, Nullable<int> id)
        {
            var listConditionParameter = listCondition != null ?
                new ObjectParameter("ListCondition", listCondition) :
                new ObjectParameter("ListCondition", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var isLogInParameter = isLogIn.HasValue ?
                new ObjectParameter("IsLogIn", isLogIn) :
                new ObjectParameter("IsLogIn", typeof(bool));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GeneralUser_GetDetailByParam_Result>("GeneralUser_GetDetailByParam", listConditionParameter, companyIdParameter, isLogInParameter, userNameParameter, passwordParameter, idParameter);
        }
    
        public virtual int GeneralUser_Insert(string name, string userName, string password, string emailAddress, string mobileNumber, Nullable<int> roleId, Nullable<bool> isLogIn, string allowedBranchIds, Nullable<System.DateTime> createdOn, Nullable<int> createdBy, Nullable<System.DateTime> updatedOn, Nullable<int> updatedBy, Nullable<int> companyId, Nullable<int> employeeId, Nullable<bool> isDeveloper)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            var mobileNumberParameter = mobileNumber != null ?
                new ObjectParameter("MobileNumber", mobileNumber) :
                new ObjectParameter("MobileNumber", typeof(string));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var isLogInParameter = isLogIn.HasValue ?
                new ObjectParameter("IsLogIn", isLogIn) :
                new ObjectParameter("IsLogIn", typeof(bool));
    
            var allowedBranchIdsParameter = allowedBranchIds != null ?
                new ObjectParameter("AllowedBranchIds", allowedBranchIds) :
                new ObjectParameter("AllowedBranchIds", typeof(string));
    
            var createdOnParameter = createdOn.HasValue ?
                new ObjectParameter("CreatedOn", createdOn) :
                new ObjectParameter("CreatedOn", typeof(System.DateTime));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var updatedOnParameter = updatedOn.HasValue ?
                new ObjectParameter("UpdatedOn", updatedOn) :
                new ObjectParameter("UpdatedOn", typeof(System.DateTime));
    
            var updatedByParameter = updatedBy.HasValue ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(int));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            var isDeveloperParameter = isDeveloper.HasValue ?
                new ObjectParameter("IsDeveloper", isDeveloper) :
                new ObjectParameter("IsDeveloper", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GeneralUser_Insert", nameParameter, userNameParameter, passwordParameter, emailAddressParameter, mobileNumberParameter, roleIdParameter, isLogInParameter, allowedBranchIdsParameter, createdOnParameter, createdByParameter, updatedOnParameter, updatedByParameter, companyIdParameter, employeeIdParameter, isDeveloperParameter);
        }
    
        public virtual ObjectResult<LK_ChallanMethod_GetListByParam_Result> LK_ChallanMethod_GetListByParam(string dB_IF_PARAM)
        {
            var dB_IF_PARAMParameter = dB_IF_PARAM != null ?
                new ObjectParameter("DB_IF_PARAM", dB_IF_PARAM) :
                new ObjectParameter("DB_IF_PARAM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LK_ChallanMethod_GetListByParam_Result>("LK_ChallanMethod_GetListByParam", dB_IF_PARAMParameter);
        }
    
        public virtual ObjectResult<LK_StudyGroup_GetListByParam_Result> LK_StudyGroup_GetListByParam(string dB_IF_PARAM, Nullable<int> companyId, Nullable<int> branchId, string allowedStudyGroupIds)
        {
            var dB_IF_PARAMParameter = dB_IF_PARAM != null ?
                new ObjectParameter("DB_IF_PARAM", dB_IF_PARAM) :
                new ObjectParameter("DB_IF_PARAM", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var allowedStudyGroupIdsParameter = allowedStudyGroupIds != null ?
                new ObjectParameter("AllowedStudyGroupIds", allowedStudyGroupIds) :
                new ObjectParameter("AllowedStudyGroupIds", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LK_StudyGroup_GetListByParam_Result>("LK_StudyGroup_GetListByParam", dB_IF_PARAMParameter, companyIdParameter, branchIdParameter, allowedStudyGroupIdsParameter);
        }
    
        public virtual ObjectResult<LK_StudyLevel_GetListByParam_Result> LK_StudyLevel_GetListByParam(string dB_IF_PARAM, Nullable<int> companyId, Nullable<int> branchId, string allowedStudyLevelIds)
        {
            var dB_IF_PARAMParameter = dB_IF_PARAM != null ?
                new ObjectParameter("DB_IF_PARAM", dB_IF_PARAM) :
                new ObjectParameter("DB_IF_PARAM", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var allowedStudyLevelIdsParameter = allowedStudyLevelIds != null ?
                new ObjectParameter("AllowedStudyLevelIds", allowedStudyLevelIds) :
                new ObjectParameter("AllowedStudyLevelIds", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LK_StudyLevel_GetListByParam_Result>("LK_StudyLevel_GetListByParam", dB_IF_PARAMParameter, companyIdParameter, branchIdParameter, allowedStudyLevelIdsParameter);
        }
    
        public virtual ObjectResult<LK_WHTaxPolicy_GetListByParam_Result> LK_WHTaxPolicy_GetListByParam(string dB_IF_PARAM, Nullable<int> companyId, Nullable<int> branchId, Nullable<int> accFeeStructureId, Nullable<int> documentStatusFeeStructure)
        {
            var dB_IF_PARAMParameter = dB_IF_PARAM != null ?
                new ObjectParameter("DB_IF_PARAM", dB_IF_PARAM) :
                new ObjectParameter("DB_IF_PARAM", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var accFeeStructureIdParameter = accFeeStructureId.HasValue ?
                new ObjectParameter("AccFeeStructureId", accFeeStructureId) :
                new ObjectParameter("AccFeeStructureId", typeof(int));
    
            var documentStatusFeeStructureParameter = documentStatusFeeStructure.HasValue ?
                new ObjectParameter("DocumentStatusFeeStructure", documentStatusFeeStructure) :
                new ObjectParameter("DocumentStatusFeeStructure", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LK_WHTaxPolicy_GetListByParam_Result>("LK_WHTaxPolicy_GetListByParam", dB_IF_PARAMParameter, companyIdParameter, branchIdParameter, accFeeStructureIdParameter, documentStatusFeeStructureParameter);
        }
    
        public virtual ObjectResult<StructureCOAAccount_GetListByParam_Result> StructureCOAAccount_GetListByParam(Nullable<int> companyId, Nullable<int> branchId, string listCondition, string coaCatagoryIds)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var listConditionParameter = listCondition != null ?
                new ObjectParameter("ListCondition", listCondition) :
                new ObjectParameter("ListCondition", typeof(string));
    
            var coaCatagoryIdsParameter = coaCatagoryIds != null ?
                new ObjectParameter("CoaCatagoryIds", coaCatagoryIds) :
                new ObjectParameter("CoaCatagoryIds", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StructureCOAAccount_GetListByParam_Result>("StructureCOAAccount_GetListByParam", companyIdParameter, branchIdParameter, listConditionParameter, coaCatagoryIdsParameter);
        }
    
        public virtual ObjectResult<StructureFeeType_GetListByParam_Result> StructureFeeType_GetListByParam(string dB_IF_PARAM, Nullable<int> companyId, Nullable<int> branchId)
        {
            var dB_IF_PARAMParameter = dB_IF_PARAM != null ?
                new ObjectParameter("DB_IF_PARAM", dB_IF_PARAM) :
                new ObjectParameter("DB_IF_PARAM", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StructureFeeType_GetListByParam_Result>("StructureFeeType_GetListByParam", dB_IF_PARAMParameter, companyIdParameter, branchIdParameter);
        }
    
        public virtual ObjectResult<StructureFeeType_GetListBySearch_Result> StructureFeeType_GetListBySearch(Nullable<int> companyId, Nullable<int> branchId, Nullable<int> inputTypeId, string inputText)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var inputTypeIdParameter = inputTypeId.HasValue ?
                new ObjectParameter("InputTypeId", inputTypeId) :
                new ObjectParameter("InputTypeId", typeof(int));
    
            var inputTextParameter = inputText != null ?
                new ObjectParameter("InputText", inputText) :
                new ObjectParameter("InputText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StructureFeeType_GetListBySearch_Result>("StructureFeeType_GetListBySearch", companyIdParameter, branchIdParameter, inputTypeIdParameter, inputTextParameter);
        }
    
        public virtual int StructureFeeType_UpSert(string dB_OperationType, Nullable<System.Guid> guID, Nullable<int> feeCatagoryId, Nullable<int> chargingMethodId, string description, Nullable<bool> isOnAdmission, Nullable<bool> isSecurity, Nullable<bool> isRefundable, Nullable<bool> isDiscount, Nullable<int> revenueAccountId, Nullable<int> assetAccountId, Nullable<int> liabilityAccountId, Nullable<int> costOfSaleAccountId, Nullable<System.DateTime> createdOn, Nullable<int> createdBy, Nullable<System.DateTime> updatedOn, Nullable<int> updatedBy, Nullable<int> branchId, Nullable<int> companyId, ObjectParameter response)
        {
            var dB_OperationTypeParameter = dB_OperationType != null ?
                new ObjectParameter("DB_OperationType", dB_OperationType) :
                new ObjectParameter("DB_OperationType", typeof(string));
    
            var guIDParameter = guID.HasValue ?
                new ObjectParameter("GuID", guID) :
                new ObjectParameter("GuID", typeof(System.Guid));
    
            var feeCatagoryIdParameter = feeCatagoryId.HasValue ?
                new ObjectParameter("FeeCatagoryId", feeCatagoryId) :
                new ObjectParameter("FeeCatagoryId", typeof(int));
    
            var chargingMethodIdParameter = chargingMethodId.HasValue ?
                new ObjectParameter("ChargingMethodId", chargingMethodId) :
                new ObjectParameter("ChargingMethodId", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var isOnAdmissionParameter = isOnAdmission.HasValue ?
                new ObjectParameter("IsOnAdmission", isOnAdmission) :
                new ObjectParameter("IsOnAdmission", typeof(bool));
    
            var isSecurityParameter = isSecurity.HasValue ?
                new ObjectParameter("IsSecurity", isSecurity) :
                new ObjectParameter("IsSecurity", typeof(bool));
    
            var isRefundableParameter = isRefundable.HasValue ?
                new ObjectParameter("IsRefundable", isRefundable) :
                new ObjectParameter("IsRefundable", typeof(bool));
    
            var isDiscountParameter = isDiscount.HasValue ?
                new ObjectParameter("IsDiscount", isDiscount) :
                new ObjectParameter("IsDiscount", typeof(bool));
    
            var revenueAccountIdParameter = revenueAccountId.HasValue ?
                new ObjectParameter("RevenueAccountId", revenueAccountId) :
                new ObjectParameter("RevenueAccountId", typeof(int));
    
            var assetAccountIdParameter = assetAccountId.HasValue ?
                new ObjectParameter("AssetAccountId", assetAccountId) :
                new ObjectParameter("AssetAccountId", typeof(int));
    
            var liabilityAccountIdParameter = liabilityAccountId.HasValue ?
                new ObjectParameter("LiabilityAccountId", liabilityAccountId) :
                new ObjectParameter("LiabilityAccountId", typeof(int));
    
            var costOfSaleAccountIdParameter = costOfSaleAccountId.HasValue ?
                new ObjectParameter("CostOfSaleAccountId", costOfSaleAccountId) :
                new ObjectParameter("CostOfSaleAccountId", typeof(int));
    
            var createdOnParameter = createdOn.HasValue ?
                new ObjectParameter("CreatedOn", createdOn) :
                new ObjectParameter("CreatedOn", typeof(System.DateTime));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var updatedOnParameter = updatedOn.HasValue ?
                new ObjectParameter("UpdatedOn", updatedOn) :
                new ObjectParameter("UpdatedOn", typeof(System.DateTime));
    
            var updatedByParameter = updatedBy.HasValue ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(int));
    
            var branchIdParameter = branchId.HasValue ?
                new ObjectParameter("BranchId", branchId) :
                new ObjectParameter("BranchId", typeof(int));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StructureFeeType_UpSert", dB_OperationTypeParameter, guIDParameter, feeCatagoryIdParameter, chargingMethodIdParameter, descriptionParameter, isOnAdmissionParameter, isSecurityParameter, isRefundableParameter, isDiscountParameter, revenueAccountIdParameter, assetAccountIdParameter, liabilityAccountIdParameter, costOfSaleAccountIdParameter, createdOnParameter, createdByParameter, updatedOnParameter, updatedByParameter, branchIdParameter, companyIdParameter, response);
        }
    }
}
