//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace office360.Models.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class StructureFeeType
    {
        public int Id { get; set; }
        public Nullable<System.Guid> GuID { get; set; }
        public Nullable<int> FeeCatagoryId { get; set; }
        public Nullable<int> ChargingMethodId { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsOnAdmission { get; set; }
        public bool IsSecurity { get; set; }
        public Nullable<bool> IsRefundable { get; set; }
        public Nullable<bool> IsDiscount { get; set; }
        public Nullable<int> RevenueAccountId { get; set; }
        public Nullable<int> AssetAccountId { get; set; }
        public Nullable<int> LiabilityAccountId { get; set; }
        public Nullable<int> CostOfSaleAccountId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
